"use client"

import { motion } from "framer-motion"
import { FileText, FileSpreadsheet, Download, FileArchive, LineChart } from "lucide-react"
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

const reportTypes = [
  {
    title: "Executive Summary PDF",
    description: "High-level overview of portfolio health, key risks, and financial predictions.",
    icon: FileText,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  {
    title: "Raw Data Export",
    description: "Export all raw project data, prediction scores, and SHAP values to Excel.",
    icon: FileSpreadsheet,
    color: "text-green-500",
    bgColor: "bg-green-500/10",
  },
  {
    title: "Risk Analysis Report",
    description: "Detailed breakdown of top risk factors across all projects in PDF format.",
    icon: LineChart,
    color: "text-amber-500",
    bgColor: "bg-amber-500/10",
  },
  {
    title: "Full Project Archive",
    description: "Download a ZIP containing all reports, documents, and logs for compliance.",
    icon: FileArchive,
    color: "text-purple-500",
    bgColor: "bg-purple-500/10",
  }
]

export default function ReportsPage() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="flex flex-col gap-6"
    >
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Reports & Exports</h1>
        <p className="text-muted-foreground">Generate and download comprehensive project analysis reports.</p>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-4">
        {reportTypes.map((report, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
          >
            <Card className="h-full flex flex-col hover:border-primary/50 transition-colors">
              <CardHeader>
                <div className={`h-12 w-12 rounded-lg ${report.bgColor} flex items-center justify-center mb-4`}>
                  <report.icon className={`h-6 w-6 ${report.color}`} />
                </div>
                <CardTitle className="text-xl">{report.title}</CardTitle>
                <CardDescription className="pt-2">{report.description}</CardDescription>
              </CardHeader>
              <CardContent className="flex-1" />
              <CardFooter>
                <Button className="w-full gap-2" variant="outline">
                  <Download className="h-4 w-4" />
                  Generate
                </Button>
              </CardFooter>
            </Card>
          </motion.div>
        ))}
      </div>
      
      <Card className="mt-4">
        <CardHeader>
          <CardTitle>Recent Generation History</CardTitle>
          <CardDescription>Reports generated in the last 7 days.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <table className="w-full text-sm text-left">
              <thead className="bg-muted text-muted-foreground font-medium border-b">
                <tr>
                  <th className="px-4 py-3">Report Name</th>
                  <th className="px-4 py-3">Format</th>
                  <th className="px-4 py-3">Generated By</th>
                  <th className="px-4 py-3">Date</th>
                  <th className="px-4 py-3 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y">
                <tr className="bg-card hover:bg-muted/30">
                  <td className="px-4 py-3 font-medium">Q3 Portfolio Risk Assessment</td>
                  <td className="px-4 py-3">PDF</td>
                  <td className="px-4 py-3">Sarah Jenkins</td>
                  <td className="px-4 py-3">Today, 10:42 AM</td>
                  <td className="px-4 py-3 text-right">
                    <Button variant="ghost" size="sm" className="h-8 text-primary">Download</Button>
                  </td>
                </tr>
                <tr className="bg-card hover:bg-muted/30">
                  <td className="px-4 py-3 font-medium">Metro Line A - Full Export</td>
                  <td className="px-4 py-3">CSV</td>
                  <td className="px-4 py-3">System Auto</td>
                  <td className="px-4 py-3">Yesterday, 11:00 PM</td>
                  <td className="px-4 py-3 text-right">
                    <Button variant="ghost" size="sm" className="h-8 text-primary">Download</Button>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </motion.div>
  )
}
